### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by meszaros-lajos-gyorgy**
This PR is about adding hungarian translation

### CODE REVIEW

**Comment by meszaros-lajos-gyorgy** [comment]
Linking #54 as a reference.

**Comment by meszaros-lajos-gyorgy** [comment]
I'm done, @sunyatasattva, please check it and see if it is any use to you.

**Comment by sunyatasattva** [comment]
Hey @meszaros-lajos-gyorgy sorry for the incredible delay, I had dropped the project for some time and also moved to a different country so I completely forgot about it. I have recently published the v. 2.0.0 of the project, however, which includes a Danish translation. So it'd be nice to include your Hungarian translation as well.

If you're still up for it, feel free to resolve the merge conflicts. Otherwise I'll do it in the next weeks :)

**Comment by meszaros-lajos-gyorgy** [comment]
All right, i'll take a look at it as soon as I have a bit of free time!

**Comment by meszaros-lajos-gyorgy** [comment]
done!

**Comment by sunyatasattva** [comment]
@meszaros-lajos-gyorgy  I guess I should have pulled and tested before merging, but there are a few things missing.

Look for `data-intro-en-US`, some strings are embedded in the HTML (I know 😓  I'm sorry, it's old code haha) and you'll need to add Hungarian in _language-swicher.html

You can test the changes by running `gulp build`, but you need to be on Node 7

**Comment by meszaros-lajos-gyorgy** [comment]
No problem! I've updated my branch, feel free to merge that one, it should contain all the stuff you've mentioned.

**Comment by sunyatasattva** [comment]
@meszaros-lajos-gyorgy Hungarian translation online! Thanks for the contribution

**Pull request merged**
